# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
        - name: event
          image: sha256:c89ab09d3d3b1b408a636bf456a1a23fda3c66f8abe7a20e30bb7fb019494151  