apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
        - name: log
          image: saadan1234/log
          ports:
            - containerPort: 5007
---
apiVersion: v1
kind: Service
metadata:
  name: log-serv
spec:
  type: ClusterIP
  selector:
    app: log
  ports:
  - name: log
    protocol: TCP
    port: 5007
    targetPort: 5007