apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: saadan1234/user
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: user-serv
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
  - name: user
    protocol: TCP
    port: 5001
    targetPort: 5001