apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view
  template:
    metadata:
      labels:
        app: view
    spec:
      containers:
        - name: view
          image: saadan1234/view
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: view-serv
spec:
  type: ClusterIP
  selector:
    app: view
  ports:
  - name: view
    protocol: TCP
    port: 3000
    targetPort: 3000